name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v3

      # Исправленный блок установки Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }} # Добавлен ключ node-version

      - name: install modules
        run: npm install

      - name: build project
        run: npm run build

      - name: build storybook
        run: npm run build:storybook

      - name: debug files
        run: ls -la # Посмотрим, есть ли тут jest.setup.js

      - name: run tests
        run: npm run test -- --no-cache

        